### ISSUE TITLE
There is no examples dir

### ISSUE THREAD

**Issue by FCO** [jonathanstowe/Raku-Linux-Fuser#1]
on the README there is this line:

```
There is an example program raku-fuser in the examples directory which provides a Raku implementation of that command.
```

But there is no examples dir... should it be `bin` dir?

**Comment by jonathanstowe** [comment]
:-)  TYPO-TASTIC!

Cheers.

**Comment by jonathanstowe** [comment]
All good now, https://github.com/jonathanstowe/Raku-Linux-Fuser/blob/master/README.md  cheers!

**Comment by FCO** [comment]
thank you!
